<?php
include("almacenes.php");
include("categorias.php");
include("componentes.php");
include("comprascab.php");
include("comprasdet.php");
include("padron.php");
include("pagoscli.php");
include("pagospro.php");
include("productos.php");
include("series.php");
include("stocks.php");
include("tipdocsope.php");
include("tipdocsper.php");
include("usuarios.php");
include("ventascab.php");
include("ventasdet.php");

?>